# Site settings
theme: jekyll-theme-cayman
title: BMW 750iL E38
author:
  name: Christoph Trautwein
  url: https://github.com/trautw
  twitter_username: trautw
  github_username:  trautw
  email: ch.trautwein@bmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hintergrund Infos zu meinem BMW 750iL E38
tagline: > # this means to ignore newlines until "baseurl:"
  Hintergrund Infos zu meinem BMW 750iL E38
baseurl: "/BMW750iL" # the subpath of your site, e.g. /blog/
url: "https://trautw.github.io" # the base hostname & protocol for your site

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
